### ISSUE TITLE
Porting core syntax to gedit

### ISSUE THREAD

**Issue by Ebedthan** [ababaian/bioSyntax#15]
Hey team,

First of all i want to focus on porting core syntax to gedit. The job done already (i need your review and critics on this job, also testing it on your laptop) is in this [folder](github.com/ababaian/bioSyntax/issues/new).  
## Completed syntax
* fasta.lang: defining colors for fasta files;
* fasta-zappo.lang: defining zappo colors for fasta files;
* fasta-hydrophobicity.lang: defining hydrophobicity colors for fasta files;
* fasta-taylor.lang: defining taylor colors for fasta files;
* fastq.lang: defining color for fastq files.  

## Remaining syntax
* sam.lang;
* bed.lang;
* pdb.lang;
* vcf.lang.  

I plan to work on theses files on a daily basis and finish this work as soon as possible.
I'm open to your remarks and wait for your analysis of this part of the project on what we have to do.

**Comment by ababaian** [comment]
@Ebedthan I used the instructions listed on our [front page](https://github.com/ababaian/bioSyntax#gedit-installation-linux) to install into gedit; everything copied over but now it's only coloring the headers and there is no nucleotide coloring at all.

```
cd ~/bioSyntax/syntax/gedit/

chmod 0644 *.lang

sudo cp *.lang /usr/share/gtksourceview-3.0/language-specs/

sudo cp bioKate.xml /usr/share/gtksourceview-3.0/styles/bioKate.xml
```

**Comment by Ebedthan** [comment]
Yes, the instructions seems a little bit more different. First of all you need to change your color scheme in gedit from classic to bioKate. So you have to add bioKate as a color scheme by selecting bioKate.xml selecting edit>preferences> font and color and click the button plus and select bioKate.xml. 
So this process will add bioKate as a new color scheme and to have things working as we want we need to select bioKAte as our color scheme after adding it.

**Comment by Ebedthan** [comment]
To avoid issues like that what do you think if we custom our [page](github.com/ababaian/bioSyntax) like the [cd-hit page](github.com/weizhongli/cdhit). Doing things like that have the advantage to have all instructions clearly explained in the wiki.  
What do you think @ababaian ?

**Comment by ababaian** [comment]
I agree; but can we migrate everything over to the wiki/it's own front page when we're closer to being done? Just consider the README.md as a draft of that page for now.

You nailed it though; I'll add an instruction to change the 'theme' to bioKate in Gedit.

**Comment by Ebedthan** [comment]
Ok you're right.

**Comment by ababaian** [comment]
## Note on Fasta
Great start, you've got the process down which means we're good to get developing : )

- [x] The main and default fasta syntax should be made context-aware.

This is a little bit tricky but if you can work it out it will help all the rest of the syntaxes to be developed quickly. Take a look at Alyssa's [fasta syntax in sublime](../blob/master/syntax/sublime/fasta.sublime-syntax). It is able to detect if a line of sequence is an amino acid and it colors them in Clustal colors or if it's Nucleotides only (ACTGUNX-.) and then it colors them as nucleotides. This concept of context aware highlighting is key to making the other formats work correctly but none of us have tried to solve this for gedit yet.

![context-aware-fasta](https://user-images.githubusercontent.com/9220907/31974073-424f5818-b8de-11e7-8977-13fe2355284e.png)

- [x] All fasta derivate formats should be named `Fasta-<SubName>` such as `Fasta-Clustal` so they come up at the same place in a context menu as opposed to just Zappo / Clustal / ...
- [x] Fasta derivative syntaxes are not coloring in headers

**Comment by Ebedthan** [comment]
Ok got it I will work on your remarks

**Comment by Ebedthan** [comment]
I think the [syntax/gedit/ folder](github.com/ababaian/bioSyntax/syntax/gedit/) can be tested now by @ababaian to see if all is correct.

**Comment by Ebedthan** [comment]
the sam.lang is not ready yet.

**Comment by ababaian** [comment]
Getting closer, good.
![fasta_eval2](https://user-images.githubusercontent.com/9220907/32029674-f872ac22-b9aa-11e7-916d-2d985502aa32.png)

`fasta.lang`
Easy
- [x] Headers are not bold
- [x] `N` character not highlighted in amino acid sequences
- [x] Nucleotide colors are quite off; can you manually set them to the colors defined in our scope issue
Challenging
- [x] For indels, you need to consider both `.` and `-` as characters which can be used for empty bases
- [ ] In the amino acid sequences, all non-first characters which are ATCG are using nucleotide colors and not amino acid colors. The best example is **Line 28** in the image above. If you add a `D` then the entire line should be treated as if it's an amino acid sequence because it's behaving like an AA sequence and not a nt sequence.
- [x] Conversely; Look at the `T` on **Line 3**, the first one is matched as an AA, green (correct) and all subsequent ones are NT, red (incorrect).

Also the fast-cyesteine should be deleted unless there's a reason for it to exist?

Finally I'm about to push a new syntax folder in `dev/syntax` which should be used for all development purposes. We should keep the top-level `syntax` folder for things which are working.

**Comment by ababaian** [comment]
Hey @lazypanda10117  + @Ebedthan ,

I just wanted to check in with both of you since it's a bit harder to communicate remotely.
You two are tasked with working on the gedit port. Ideally we all will have the core syntaxes done for the next meeting (~Nov 17th). I know it's been difficult to learn regex / syntax highlighting on your own but both of your code is looking better with each iteration.

One thing which we're slowly learning is that some of the more advanced syntaxes (PDB, SAM, VCF) will require internal logic (if --> then) to work correctly. So far really none of us have figured this out for the gedit syntax. @echu113 is our experienced programmer and is going to spend a few days looking into the sam format for gedit to see if he can find a logical way to solve this. My recommendation for all of you is to read some gedit .lang code for complex syntaxes and get a better feeling for how to use that language and share what you find with each other. If you guys really get to an impasse let me know and the others can look into helping out too.

**Comment by pan-chu** [comment]
https://github.com/ababaian/bioSyntax/issues/22

**Comment by ababaian** [comment]
Hey @Ebedthan + @lazypanda10117,

I think I might have cracked the gedit/gtksourceview syntax for getting 'robust column selection'

Check out [Fasta Index Language File](https://github.com/ababaian/bioSyntax/blob/master/syntax/gedit/faidx.lang) for an example of the logic. It's the same thing as in sublime / less where nested contexts can be used to select by column. This should make SAM/VCF/BED/GTF files much much easier to deal with.

![faidx-gedit](https://user-images.githubusercontent.com/9220907/32995224-42d3f74c-cd26-11e7-88b9-64a513b49ec2.png)

**Comment by ababaian** [comment]
Helpful link for future reference: https://developer.gnome.org/gtksourceview/stable/lang-reference.html
