### ISSUE TITLE
Polish SAM syntax highlighting capability

### ISSUE THREAD

**Issue by pan-chu** [ababaian/bioSyntax#22]
* use column based selection logic in SAM syntax highlighting (update sublime)
* port over to gedit

**Comment by pan-chu** [comment]
1726408ea7f2b827ed8eda46a3b17fa423118292 - updated SAM syntax in sublime to use column based logic as proposed by Artem.. works great! See screenshot below. Note that theme/color hasn't yet been finalized. 

![screen shot 2017-11-06 at 1 19 47 pm](https://user-images.githubusercontent.com/1761710/32464555-4801de54-c2f5-11e7-81a5-20a347342636.png)

Will work on porting to gedit now.

**Comment by Ebedthan** [comment]
great @echu113. Let's go.

**Comment by ababaian** [comment]
So a few details from less. 

Do you see how in column 6 chr12 is in red? That's because it's not a "=" sign and the pair of that read is on another chromosome. Can you make the coordinate of the pair (column 7) be in a matching red when column 6 is not an "=" ? or simply grayed out when they are "." and "0"

**Comment by pan-chu** [comment]
something like this? pushing soon...

![screen shot 2017-11-07 at 11 56 24 am](https://user-images.githubusercontent.com/1761710/32514748-cd520a30-c3b2-11e7-8b5c-4bc5dff78849.png)

**Comment by ababaian** [comment]
Yeah like that, make sure to grab the `*` cases as well.

**Comment by ababaian** [comment]
I have to polish less-sam format myself a bit more but [it's looking great](https://github.com/ababaian/bioSyntax/issues/16). There are some non-standard highlights which I think are essential to implement in all contexts. We can discuss adding more or removing these, it's just some ideas.

## .sam Features
- [x] Header `@HD SO:` if it's `coordinate` or `queryname` then highlight in blue or green; if it's `unsorted` or `unknown` then highlight in red. This is an important tag to distinguish for downstream application compatibility   
- [x] Column 2: Flag. If FLAG is greater then 512, color text in red since read fails QC / is Supplementary / PCR duplicate. Otherwise color as numeric.
- [x] Column 5: MAPQ Value: add gradient coloring to map quality scores. Rough groupings are OK of 255,0-9;    10-19;      20-29;     30-39;      40+
- [x] Column 6: CIGAR string; color based on the alignment. I have this working beautifully in sam-less. Refer to the sam specification file and/or the sam.lang file for less.
- [x] Column 7/8: Chromosome colors for matching contigs; contrasting color for mis-matching or unmapped.
- [x] Column 10: Nucleotide colors
- [x] Column 11: PHRED gradient colors. So far I like the b/w scheme the most but if you're willing to play around with this and see if there's a better color gradient we can use which works with light and dark themes this will be good
- [x] Column 12+: Supplementary tags can be colored based on the type of data they are storing (Z, I, B...). Are there any special tags which we would like to make special cases for like Concordent vs. Discordant read pairs?

Edit: added all listed features to sublime sam

**Comment by ababaian** [comment]
We had the medical genetics Research Day today, bioinformaticians I talked to loved bioSyntax :+1: 

First question I got from one of them "Do you do CIGAR string highlighting?"

Edit: I've now added CIGAR string highlighting to sam-less. Makes it way more legible.
